name: Angular build and test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install web lib deps
        working-directory: ./renderers/lit
        run: npm i

      - name: Build web lib
        working-directory: ./renderers/lit
        run: npm run build

      - name: Install renderer deps
        working-directory: ./renderers/angular
        run: npm i

      - name: Build Angular renderer
        working-directory: ./renderers/angular
        run: npm run build

      - name: Install top-level deps
        working-directory: ./samples/client/angular
        run: npm i

      - name: Build contact sample
        working-directory: ./samples/client/angular
        run: npm run build contact

      - name: Build restaurant sample
        working-directory: ./samples/client/angular
        run: npm run build restaurant

      - name: Build Rizzchart sample
        working-directory: ./samples/client/angular
        run: npm run build rizzcharts

      - name: Build Orchestrator
        working-directory: ./samples/client/angular
        run: npm run build orchestrator
